[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "contracts/out"
cache_path = "contracts/cache"
libs = ["node_modules"]
solc_version = "0.8.28"
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "./fixtures" }]
remappings = ["@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"]

